# Generated by Django 2.0.7 on 2018-07-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedstoneFeedsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default RSS Name', max_length=64)),
                ('url', models.CharField(default='', max_length=1024)),
                ('fetch_time', models.DateTimeField(default='')),
                ('alive_status', models.IntegerField(default=0)),
                ('spider_type', models.IntegerField(default=0)),
                ('fail_reason', models.CharField(max_length=512)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'rs_feeds',
            },
        ),
    ]
