# Generated by Django 2.0.7 on 2018-07-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedstoneSpiderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Spider', max_length=128)),
                ('filename', models.CharField(default='default_rss.py', max_length=256)),
                ('class_name', models.CharField(default='DefaultRSSClassName', max_length=256)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'rs_spider',
            },
        ),
    ]
